name: Lint with ESLint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  eslint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install modules
        run: npm ci
        
      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx
        continue-on-error: true
        
      - name: Save Code Linting Report
        run: npx eslint --output-file eslint_report.json --format json src
        continue-on-error: true
        
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint_report.json"

      - name: Upload ESLint report
        uses: actions/upload-artifact@v2
        with:
          name: eslint_report.json
          path: eslint_report.json
