name: Lint with ESLint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  eslint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install modules
        run: npm ci
        
      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx
