name: Publish

on: 
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Bump type'     
        required: true
        default: 'minor' 
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  bump:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci

      - name: ReleaseIt
        run: npm run release
      
  release:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Build Changelog
        id: github_release_build
        uses: mikepenz/release-changelog-builder-action@v2.4.3
        with:
          configuration: "./.github/workflows/changelog-config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Read version
        id: app_version
        run: >-
          echo "::set-output name=VERSION::$(
            npm pkg get version |
            sed 's/"//g'
          )"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with: 
          tag_name: v${{ steps.app_version.outputs.VERSION }}
          release_name: v${{ steps.app_version.outputs.VERSION }}
          body: ${{ steps.github_release_build.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
